[esp-wifi]
heap_size = 98304
rx_queue_size = 15
tx_queue_size = 3
static_rx_buf_num = 32
dynamic_rx_buf_num = 32
dynamic_tx_buf_num = 32
ampdu_rx_enable = 0
ampdu_tx_enable = 0
rx_ba_win = 28
max_burst_size = 6
country_code = "01"